name       : gestures
version    : 0.1.5
release    : 2
source     :
    - https://gitlab.com/cunidev/gestures/-/archive/0.1.5/gestures-0.1.5.zip : 26303e510abce04c9712e1dd8482d545e275136305ce2d80b49f7f223608b9cd
license    : GPL-3.0-or-later
component  : desktop
summary    : Modern, minimal GUI app for libinput-gestures
description: |
    A minimal Gtk+ GUI app for Linux touchpad gestures, based on the popular libinput-gestures tool.
builddeps  :
    - python-setuptools
rundeps    :
    - libinput-gestures
    - python3-gobject
setup      : |
    %python3_setup
install    : |
    %python3_install
