name       : gestures
version    : 0.1.4.1
release    : 1
source     :
    - https://gitlab.com/cunidev/gestures/-/archive/0.1.4.1/gestures-0.1.4.1.zip : 1fa0ca191af1e2594c53af6f49237bfccbd808c1cdc63dc87388e3810bfe02bb
license    : GPL-3.0-or-later
component  : desktop
summary    : Modern, minimal GUI app for libinput-gestures
description: |
    A minimal Gtk+ GUI app for Linux touchpad gestures, based on the popular libinput-gestures tool.
builddeps :
    - python-setuptools
rundeps   :
    - libinput-gestures
    - python3-gobject
setup    : |
    %python3_setup
install  : |
    %python3_install
