name       : gestures
version    : 0.2.2
release    : 4
source     :
    - https://gitlab.com/cunidev/gestures/-/archive/0.2.2/gestures-0.2.2.zip : 68051ae8503845d141f7dea53048761a27242f3dd433e68b68913ab9842e87ad
license    : GPL-3.0-or-later
component  : desktop
summary    : Modern, minimal GUI app for libinput-gestures
description: |
    A minimal Gtk+ GUI app for Linux touchpad gestures, based on the popular libinput-gestures tool.
builddeps  :
    - python-setuptools
rundeps    :
    - libinput-gestures
    - python3-gobject
setup      : |
    %python3_setup
install    : |
    %python3_install
