name       : gestures
version    : 0.3.1
release    : 8
source     :
    - https://gitlab.com/cunidev/gestures/-/archive/0.3.1/gestures-0.3.1.tar.gz : 7483843e08508f6e31ebc36a2dfb3cf540a485b502736e23e40a70bfc4110890
license    : GPL-3.0-or-later
component  : desktop
summary    : Modern, minimal GUI app for libinput-gestures
description: |
    A minimal Gtk+ GUI app for Linux touchpad gestures, based on the popular libinput-gestures tool.
rundeps    :
    - libinput-gestures
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
